query getAllCharities {
  CHC {
    getCharities(filters: {}) {
      aggregate {
        finances {
          latestIncome {
            buckets {
              key
              name
              count
              sum
            }
          }
        }
      }
      count
    }
  }
}
