fragment allBucket on Aggregation {
  buckets {
    key
    name
    count
    sumIncome
  }
}

query getCharityAggregation($filters: FilterCHCInput!, $limit: PageLimit = 30, $skip: Int = 0) {
  CHC {
    getCharities(filters: $filters) {
      aggregate {
        income {
          ...allBucket
        }
        causes {
          ...allBucket
        }
				beneficiaries {
          ...allBucket
        }
				operations {
          ...allBucket
        }
        areas {
          ...allBucket
        }
      }
      count
      list(limit: $limit, skip: $skip) {
        id
        name
        activities
        areas {	
          name
          id
        }
        income {
          latest {
            date
            total
          }
        }
        geo {
          latitude
          longitude
          region
        }
        website
      }
    }
  }
}
