query getCharityList($filters: FilterCHCInput!, $limit: PageLimit = 30, $skip: Int = 0) {
  CHC {
    getCharities(filters: $filters) {
      count
      list(limit: $limit, skip: $skip) {
        id
        name
        activities
        areas {	
          name
          id
        }
        income {
          latest {
            date
            total
          }
        }
      }
    }
  }
}
