query getCharityList(
  $filters: FilterCHCInput!
  $limit: PageLimit = 30
  $skip: Int = 0
  $allFinances: Boolean = false
) {
  CHC {
    getCharities(filters: $filters) {
      count
      list(limit: $limit, skip: $skip) {
        id
        names {
          value
          primary
        }
        activities
        areas {
          name
          id
        }
        finances(all: $allFinances) {
          income
          spending
          financialYear {
            end
          }
        }
        orgIds {
          id
        }
        geo {
          latitude
          longitude
          region
          country
        }
        registrations(all: true) {
          registrationDate
          removalDate
        }
        website
      }
    }
  }
}
