fragment allBucket on Aggregation {
  buckets {
    key
    name
    count
    sum
  }
}

query getCharityAggregation(
  $filters: FilterCHCInput!
  $limit: PageLimit = 30
  $skip: Int = 0
  $allFinances: Boolean = false
  $sort: SortCHC = default
) {
  CHC {
    getCharities(filters: $filters) {
      aggregate {
        finances {
          latestSpending {
            ...allBucket
          }
        }
        causes {
          ...allBucket
        }
        beneficiaries {
          ...allBucket
        }
        operations {
          ...allBucket
        }
        areas {
          ...allBucket
        }
        geo {
          region {
            ...allBucket
          }
          country {
            ...allBucket
          }
        }
      }
      count
      list(limit: $limit, skip: $skip, sort: $sort) {
        id
        names {
          value
          primary
        }
        activities
        areas {
          name
          id
        }
        finances(all: $allFinances) {
          income
          spending
          financialYear {
            end
          }
        }
        orgIds {
          id
        }
        geo {
          latitude
          longitude
          region
          country
        }
        registrations(all: true) {
          registrationDate
          removalDate
        }
        website
      }
    }
  }
}
