
query getCharityAggregation(
  $filters: FilterCHCInput!
  $limit: PageLimit = 30
  $skip: Int = 0
) {
  CHC {
    getCharities(filters: $filters) {
      count
      list(limit: $limit, skip: $skip) {
%s
      }
    }
  }
}
