import re
from collections import Counter
from typing import Optional

from ngo_explorer.classes.charity import Charity

STOP_WORDS = [
    # from https://gist.github.com/sebleier/554280
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now",
    # others
    "throughout",
    "around",
    "charity",
    "charitable",
]


def word_cloud(
    charity_data: Optional[list["Charity"]] = None,
) -> dict[str, int]:
    if not charity_data:
        return {}
    alpha_regex = r"[^a-zA-Z]+"

    words: Counter[str] = Counter()
    for charity in charity_data:
        if not charity.activities:
            continue
        activities = charity.activities.split()
        for word in activities:
            word = re.sub(alpha_regex, "", word.lower())
            if word in STOP_WORDS or len(word) <= 3:
                continue
            words.update([word])

    return dict(words.most_common(50))
